// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnKqPu0YKzgFULkN-StxfPyg0jhP6GIEE',
    appId: '1:992224530589:ios:b3d5af5c27522b664bc474',
    messagingSenderId: '992224530589',
    projectId: 'skillbridge-118ba',
    storageBucket: 'skillbridge-118ba.firebasestorage.app',
    iosBundleId: 'com.example.skillbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEga2RMKafwZa6h6_TytdmBU7L_lnID6k',
    appId: '1:992224530589:web:e6ac48f5822afd904bc474',
    messagingSenderId: '992224530589',
    projectId: 'skillbridge-118ba',
    authDomain: 'skillbridge-118ba.firebaseapp.com',
    storageBucket: 'skillbridge-118ba.firebasestorage.app',
    measurementId: 'G-KZJQM7MJK3',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEga2RMKafwZa6h6_TytdmBU7L_lnID6k',
    appId: '1:992224530589:web:e6ac48f5822afd904bc474',
    messagingSenderId: '992224530589',
    projectId: 'skillbridge-118ba',
    authDomain: 'skillbridge-118ba.firebaseapp.com',
    storageBucket: 'skillbridge-118ba.firebasestorage.app',
    measurementId: 'G-KZJQM7MJK3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnKqPu0YKzgFULkN-StxfPyg0jhP6GIEE',
    appId: '1:992224530589:ios:b3d5af5c27522b664bc474',
    messagingSenderId: '992224530589',
    projectId: 'skillbridge-118ba',
    storageBucket: 'skillbridge-118ba.firebasestorage.app',
    iosBundleId: 'com.example.skillbridge',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3dn3Qwm-WpY4VhrV3iHC7d0Z6NPWZlh8',
    appId: '1:992224530589:android:ba72331ef45906d94bc474',
    messagingSenderId: '992224530589',
    projectId: 'skillbridge-118ba',
    storageBucket: 'skillbridge-118ba.firebasestorage.app',
  );

}